# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20160520_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='userId',
            new_name='membershipId',
        ),
    ]
